# Generated by Django 5.1.2 on 2024-11-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_rename_quote_id_quotetag_quote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(related_name="quotes", to="quotes.tag"),
        ),
        migrations.DeleteModel(
            name="QuoteTag",
        ),
    ]
