# Generated by Django 5.1.2 on 2024-11-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_quote_tags_delete_quotetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
