# Generated by Django 5.1.2 on 2024-11-08 13:01

from django.db import migrations
from django.utils.text import slugify


def fill_slug_for_existing_authors(apps, schema_editor):
    Author = apps.get_model("quotes", "Author")
    for author in Author.objects.all():
        if not author.slug:  # перевіряємо, чи поле slug порожнє
            author.slug = slugify(author.fullname)
            author.save()


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0005_author_slug"),
    ]

    operations = [
        migrations.RunPython(fill_slug_for_existing_authors),
    ]
